// examples/nextjs/src/app/page.tsx
import styles from './page.module.scss';
import { buildClient } from '@reactionary/core';
import { withAlgoliaCapabilities } from '@reactionary/provider-algolia';

export default async function Index() {
  const client = buildClient([
    withAlgoliaCapabilities(
      {
        apiKey: '1f3c6a681eadb77fbf42ca148ace0767',
        appId: 'G10R4JEVO1',
        indexName: 'martinrogne-products',
      },
      { search: true, products: true }
    ),
  ]);

  const result = await client.search.get({
    term: 'glass',
    facets: [],
    page: 0,
    pageSize: 20
  });


  /*
   * Replace the elements below with your own.
   *
   * Note: The corresponding styles are in the ./index.scss file.
   */
  return (
    <div className={ styles.host }>
      <header>
        <input />
      </header>
      <main>
        <aside>
          {
            result.facets.map(facet =>
              <details key={ facet.identifier.id }>
                <summary>
                  { facet.name }
                </summary>
                <div>
                  {
                      facet.values.map(facetValue =>
                        <label key={ facetValue.identifier.id }>
                          <span>{ facetValue.name }</span>
                          <span>{ facetValue.count }</span>
                          <input type="checkbox" checked={ facetValue.active } readOnly />
                        </label>
                      )
                  }
                </div>
              </details>
            )
          }
        </aside>
        <section>
          {
            result.products.map(product =>
              <article key={ product.identifier.id }>
                <img src={product.image.replace('w_200', 'w_200,h_200')} />
                <h3>{ product.name }</h3>
              </article>
            )
          }
        </section>
      </main>
      <footer>
        <button>&lt;</button>
        <button>&gt;</button>
      </footer>
    </div>
  );
}

// examples/angular/src/app/app.component.ts
import { Component, resource, signal } from '@angular/core';
import { RouterModule } from '@angular/router';
import { buildClient } from '@reactionary/core';
import { withAlgoliaCapabilities } from '@reactionary/provider-algolia';

@Component({
  imports: [RouterModule],
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
})
export class AppComponent {
  protected client = buildClient([
    withAlgoliaCapabilities(
      {
        apiKey: '1f3c6a681eadb77fbf42ca148ace0767',
        appId: 'G10R4JEVO1',
        indexName: 'martinrogne-products'
      },
      { search: true, products: true }
    )
  ]);

  protected pageSize = signal(20);
  protected page = signal(0);
  protected term = signal('glass');
  protected facets = signal([]);

  protected search = resource({
    request: () => ({ pageSize: this.pageSize(), page: this.page(), term: this.term(), facets: this.facets() }),
    loader: async ({ request }) => {
      return this.client.search.get(request);
    }
  });
}

<header>
    <input (keydown)="this.term.set(inputTerm.value)" #inputTerm/>
</header>
<main>
    <aside>
        @for (facet of search()?.facets; track $index) {
            <details [open]="true">
                <summary>{{ facet.name }}</summary>
                
                <div class="content">
                    @for (value of facet.values; track $index) {
                        <label>
                            <span>{{ value.name }}</span>
                            <span>{{ value.count }}</span>
                            <input type="checkbox" (click)="toggleFacet(value.identifier)" [checked]="value.active"/>
                        </label>
                    }
                </div>
            </details>
        }
    </aside>
    <section>
        @for (product of search()?.products; track $index) {
            <article>
                <img [src]="product.image.replace('w_200', 'w_200,h_200')" [alt]="product.name" />
                <h3>{{ product.name }}</h3>
            </article>
        }
    </section>
</main>
<footer>
    <button (click)="previousPage()" [disabled]="hasPrevious()">
        &lt;
    </button>
    <button (click)="nextPage()" [disabled]="hasNext()">
        &gt;
    </button>
</footer>
